### ISSUE TITLE
Similify Login process :: IDEA

### ISSUE THREAD

**Issue by ghost** [Kiritsu/ShareY#1]
Hi @Kiritsu,

Would you consider such feature passwordless login like https://github.com/PwdLess/Cierge where it can cut out the registration and forgot password screen have one screen where you can login using otp pin or magic link?

**Comment by Kiritsu** [comment]
Hello!

It could be possible but only available for users that have specified a valid e-mail when they signed-up and/or when sign-up is enabled. Because e-mail is facultative and their token is the only way to authenticate. 

I'll look into adding this feature, thank you!

**Comment by nicotravassos** [comment]
Thank you @Kiritsu

**Comment by Kiritsu** [comment]
Hello, I have been working on it a bit. Currently, it's not sending an email or anything (I still need to work on this part!) but it's creating a one-time `token`/`auth link` for the specified `email`

# Step 1: Login
![Login_Page](https://storage.alnmrc.com/D2RarKTIx4.png)

# Step 2: Enter a valid user's e-mail
![Enter_Email](https://storage.alnmrc.com/pNcqqUmtJY.png)
If you entered a wrong e-mail/empty field, it will return an error message.

# Step 3: One-Time-Token received
![OTT_Received](https://storage.alnmrc.com/a0oG9amPX9.png)
Technically, you should have received in your e-mails either a link: `https://localhost:44331/auth/login/ott/69293c88-48c3-472f-b922-10f91adb6b39` or your one-time-token: `69293c88-48c3-472f-b922-10f91adb6b39`

# Step 4: Validate One-Time-Token
## Use the URL:
It will directly log you in and redirect you to the main page.

## Manually enter the one-time-token:
On the login page, click `Enter One-Time-Token` which redirects to `~/auth/login/ott`
![Enter_OTT](https://storage.alnmrc.com/8jP3v6SLvj.png)
Then click login and it will log you in, redirect you to the main page.

Of course, then, the one-time-token is getting invalidated by a service. By default, a one-time-token has a duration life of 30 minutes. I will add a way to configure that option.

Is that the kind of feature you wanted?

**Comment by Kiritsu** [comment]
The views are pretty simple for now. I want a back end that works *fine*, then I'll be working on a front end.

**Comment by nicotravassos** [comment]
Hi @Kiritsu,

Wow it looks great but may I ask if it would be ideal to rather have the token input on another page for security reason like bruit force token inputs and this allows users to use recapture on the token input page please see examples below:

https://github.com/PwdLess/Cierge/blob/master/Cierge/Filters/ValidateRecaptchaAttribute.cs
https://github.com/PwdLess/Cierge/blob/master/Cierge/Views/Account/TokenInput.cshtml

Other security enhancers could be:
- [ ] Allow signup's so if user does not exist create the user and send pin, if signup capability is turned off then say example "If the email you specified exists in our system, we've sent a opt or magic link to it." this is nice for security so nobody knows if the account actually exists so they can guess the otp.
- [ ] Block account based on many otp tries
- [ ] Implement hidden recaptcha like https://github.com/PwdLess/Cierge/blob/master/Cierge/Filters/ValidateRecaptchaAttribute.cs where its based on score
- [ ] XSS: (This is not important) Example: https://github.com/johnstaveley/SecurityEssentials
  - [ ] Incorporation of the WPL AntiXSS library to encode all output
  - [ ] Enforce the location of the scripts/assets/actions the browser can run using a content security 
    policy header
  - [ ] Feature Policy disallows features used in the browser such as camera, sync-xhr etc
  - [ ] Enables browser's anti-xss capabilities by sending the XSS-Protection header

**Comment by Kiritsu** [comment]
Hello,

Thank you for your feedback. I'll try to implement reCAPTCHA's services.

`Allow signup's so if user does not exist create the user and send pin`
-> When you signup, it directly gives you your token, so yeah, I could auto-create an account and give them their token in case the user doesn't exist, but what happens if the user misspelled his e-mail/token? Would it create an account for nothing?

`if signup capability is turned off then say example "If the email you specified exists in our system, we've sent a opt or magic link to it."`
-> Good idea, haven't really thought of this and it's indeed better.

`Block account based on many otp tries`
-> Imagine an attacker has an e-mail list and tries to force-brute one of them, wouldn't it be better to block the access to the attacker instead of the account itself?

`Implement hidden recaptcha`
-> Sure! The user will also be able to enable/disable it etc.

And I have never heard of `XSS`, so I'm going to read what it is through your link.

Thank you very much for your contribution.

**Comment by nicotravassos** [comment]
> When you signup, it directly gives you your token, so yeah, I could auto-create an account and give them their token in case the user doesn't exist, but what happens if the user misspelled his e-mail/token? Would it create an account for nothing?

If mail address does not exist and is misspelled by end user and token has not been accepted within 5 minutes then delete the account so it can conpare on created timestamp is greater than 5 minutes and token has not been used delete the account. Lol I guess that can work but it feel like a hack remember the whole point is to move away from register forms and forget password. This how we could also handle it https://github.com/PwdLess/Cierge/blob/master/Cierge/Views/Account/Register.cshtml if mail address is new then prompt a register form I do not think that is a bad idea.

> Block account based on many otp tries
> Imagine an attacker has an e-mail list and tries to force-brute one of them, wouldn't it be better to block the access to the attacker instead of the account itself?

Great Idea !!

> And I have never heard of XSS, so I'm going to read what it is through your link.

This is not important but nice to have 

> Cross-Site Scripting (XSS) attacks are a type of injection, in which malicious scripts are injected into otherwise benign and trusted websites. XSS attacks occur when an attacker uses a web application to send malicious code, generally in the form of a browser side script, to a different end user.

**Comment by nicotravassos** [comment]
Hi @Kiritsu,

Do you have anything to check-in?

**Comment by Kiritsu** [comment]
Hello! Haven't got time to work on it yet. Also, holiday summer is over today so I will work depending on the free time I got after school days! :)

**Comment by nicotravassos** [comment]
Sounds great thanks!

**Comment by nicotravassos** [comment]
Hi @Kiritsu,

Has the below redirect been fixed so I can add auth email and otp on one screen frontend changes tonight

> Thanks!
> 
> I added the form for validating an ott. If it fails it'll redirect to the other page tho. I'll change that later in the controller. (you can do it if you want to)

**Comment by Kiritsu** [comment]
Not yet but feel free to do the front-end changes, it shouldn't break anything.

**Comment by nicotravassos** [comment]
Will do :+1:

**Comment by nicotravassos** [comment]
Hi @Kiritsu, So the image I posted early do you want the email and otp fields displayed or only show otp field when email otp has been request?

**Comment by Kiritsu** [comment]
Let the email field in case for some reasons user has to request another otp

**Comment by nicotravassos** [comment]
Okay cool so I will do it exactly like this but with buttons ofcause
![64774059-c5db5b80-d553-11e9-85b8-b9447d2e1c84](https://user-images.githubusercontent.com/55157226/65044824-f0675300-d95d-11e9-96f9-f66415c9e305.png)
